package com.campofrio.materiales.model.bc.am;

import com.campofrio.materiales.model.bc.am.common.AppModulePeticionesAM;
import com.campofrio.materiales.model.bc.views.MensajesVOImpl;
import com.campofrio.materiales.model.bc.views.MensajesVORowImpl;
import com.campofrio.materiales.model.bc.views.PeticionesVOImpl;

import com.campofrio.materiales.model.bc.views.PeticionesVORowImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 07 10:39:34 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModulePeticionesAMImpl extends ApplicationModuleImpl implements AppModulePeticionesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModulePeticionesAMImpl() {
    }

    /**
     * Container's getter for Peticiones1.
     * @return Peticiones1
     */
    public PeticionesVOImpl getPeticiones1() {
        return (PeticionesVOImpl) findViewObject("Peticiones1");
    }

    /**
     * Container's getter for Mensajes1.
     * @return Mensajes1
     */
    public MensajesVOImpl getMensajes1() {
        return (MensajesVOImpl) findViewObject("Mensajes1");
    }

    /**
     * Container's getter for MensajesPeticionLK1.
     * @return MensajesPeticionLK1
     */
    public ViewLinkImpl getMensajesPeticionLK1() {
        return (ViewLinkImpl) findViewLink("MensajesPeticionLK1");
    }
    
    public void createXPeticionesWithXMensajesEachOne(Integer x){
        for (int i = 0; i<x; i++) {
            PeticionesVORowImpl peticion = (PeticionesVORowImpl) getPeticiones1().createRow();
            peticion.setAsunto("Asunto " + i);
            peticion.setDescripcion("Descripcion " + i);
            for (int j = 0; j<x; j++) {
                MensajesVORowImpl mensaje = (MensajesVORowImpl) peticion.getMensajes().createRow();
                mensaje.setCuerpoMensaje("Mensaje " + i + " : " + j);
            }
        }
        this.getDBTransaction().commit();
        this.getPeticiones1().clearCache();
        this.getPeticiones1().executeQuery();
        this.getMensajes1().clearCache();
        this.getMensajes1().executeQuery();
    }
    
    public void deleteAllPeticiones() {
        Row first = getPeticiones1().first();
        if (first!=null) {
            getPeticiones1().removeCurrentRow();
            deleteAllPeticiones();
        } else {
            this.getDBTransaction().commit();    
        }
    }
}

