package com.test.materiales.model.bc.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 07 10:40:59 CET 2017
// ---------------------------------------------------------------------
public interface AppModulePeticionesAM extends ApplicationModule {
    void createXPeticionesWithXMensajesEachOne(Integer x);

    void deleteAllPeticiones();
}

