package com.campofrio.materiales.model.bc.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 07 10:40:10 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MensajesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MensajesVOImpl() {
    }
}

