package com.campofrio.materiales.model.bc.views;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 07 10:38:20 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PeticionesVORowImpl extends ViewRowImpl {
    public static final int ENTITY_PETICIONESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Asunto,
        Descripcion,
        EstadosPeticionId,
        FechaModificacion,
        Id,
        UsuarioCreacion,
        UsuarioModificacion,
        FechaCreacion,
        AdjuntoBlob,
        AdjuntoClob,
        AdjuntoExtension,
        AdjuntoNombre,
        Mensajes,
        EstadosRO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ASUNTO = AttributesEnum.Asunto.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int ESTADOSPETICIONID = AttributesEnum.EstadosPeticionId.index();
    public static final int FECHAMODIFICACION = AttributesEnum.FechaModificacion.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int USUARIOCREACION = AttributesEnum.UsuarioCreacion.index();
    public static final int USUARIOMODIFICACION = AttributesEnum.UsuarioModificacion.index();
    public static final int FECHACREACION = AttributesEnum.FechaCreacion.index();
    public static final int ADJUNTOBLOB = AttributesEnum.AdjuntoBlob.index();
    public static final int ADJUNTOCLOB = AttributesEnum.AdjuntoClob.index();
    public static final int ADJUNTOEXTENSION = AttributesEnum.AdjuntoExtension.index();
    public static final int ADJUNTONOMBRE = AttributesEnum.AdjuntoNombre.index();
    public static final int MENSAJES = AttributesEnum.Mensajes.index();
    public static final int ESTADOSRO1 = AttributesEnum.EstadosRO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PeticionesVORowImpl() {
    }

    /**
     * Gets PeticionesEO entity object.
     * @return the PeticionesEO
     */
    public EntityImpl getPeticionesEO() {
        return (EntityImpl) getEntity(ENTITY_PETICIONESEO);
    }

    /**
     * Gets the attribute value for ASUNTO using the alias name Asunto.
     * @return the ASUNTO
     */
    public String getAsunto() {
        return (String) getAttributeInternal(ASUNTO);
    }

    /**
     * Sets <code>value</code> as attribute value for ASUNTO using the alias name Asunto.
     * @param value value to set the ASUNTO
     */
    public void setAsunto(String value) {
        setAttributeInternal(ASUNTO, value);
    }

    /**
     * Gets the attribute value for DESCRIPCION using the alias name Descripcion.
     * @return the DESCRIPCION
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPCION using the alias name Descripcion.
     * @param value value to set the DESCRIPCION
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
    }

    /**
     * Gets the attribute value for ESTADOS_PETICION_ID using the alias name EstadosPeticionId.
     * @return the ESTADOS_PETICION_ID
     */
    public Integer getEstadosPeticionId() {
        return (Integer) getAttributeInternal(ESTADOSPETICIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTADOS_PETICION_ID using the alias name EstadosPeticionId.
     * @param value value to set the ESTADOS_PETICION_ID
     */
    public void setEstadosPeticionId(Integer value) {
        setAttributeInternal(ESTADOSPETICIONID, value);
    }

    /**
     * Gets the attribute value for FECHA_MODIFICACION using the alias name FechaModificacion.
     * @return the FECHA_MODIFICACION
     */
    public Timestamp getFechaModificacion() {
        return (Timestamp) getAttributeInternal(FECHAMODIFICACION);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_MODIFICACION using the alias name FechaModificacion.
     * @param value value to set the FECHA_MODIFICACION
     */
    public void setFechaModificacion(Timestamp value) {
        setAttributeInternal(FECHAMODIFICACION, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for USUARIO_CREACION using the alias name UsuarioCreacion.
     * @return the USUARIO_CREACION
     */
    public String getUsuarioCreacion() {
        return (String) getAttributeInternal(USUARIOCREACION);
    }

    /**
     * Sets <code>value</code> as attribute value for USUARIO_CREACION using the alias name UsuarioCreacion.
     * @param value value to set the USUARIO_CREACION
     */
    public void setUsuarioCreacion(String value) {
        setAttributeInternal(USUARIOCREACION, value);
    }

    /**
     * Gets the attribute value for USUARIO_MODIFICACION using the alias name UsuarioModificacion.
     * @return the USUARIO_MODIFICACION
     */
    public String getUsuarioModificacion() {
        return (String) getAttributeInternal(USUARIOMODIFICACION);
    }

    /**
     * Sets <code>value</code> as attribute value for USUARIO_MODIFICACION using the alias name UsuarioModificacion.
     * @param value value to set the USUARIO_MODIFICACION
     */
    public void setUsuarioModificacion(String value) {
        setAttributeInternal(USUARIOMODIFICACION, value);
    }

    /**
     * Gets the attribute value for FECHA_CREACION using the alias name FechaCreacion.
     * @return the FECHA_CREACION
     */
    public Timestamp getFechaCreacion() {
        return (Timestamp) getAttributeInternal(FECHACREACION);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_CREACION using the alias name FechaCreacion.
     * @param value value to set the FECHA_CREACION
     */
    public void setFechaCreacion(Timestamp value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**
     * Gets the attribute value for ADJUNTO_BLOB using the alias name AdjuntoBlob.
     * @return the ADJUNTO_BLOB
     */
    public BlobDomain getAdjuntoBlob() {
        return (BlobDomain) getAttributeInternal(ADJUNTOBLOB);
    }

    /**
     * Sets <code>value</code> as attribute value for ADJUNTO_BLOB using the alias name AdjuntoBlob.
     * @param value value to set the ADJUNTO_BLOB
     */
    public void setAdjuntoBlob(BlobDomain value) {
        setAttributeInternal(ADJUNTOBLOB, value);
    }

    /**
     * Gets the attribute value for ADJUNTO_CLOB using the alias name AdjuntoClob.
     * @return the ADJUNTO_CLOB
     */
    public ClobDomain getAdjuntoClob() {
        return (ClobDomain) getAttributeInternal(ADJUNTOCLOB);
    }

    /**
     * Sets <code>value</code> as attribute value for ADJUNTO_CLOB using the alias name AdjuntoClob.
     * @param value value to set the ADJUNTO_CLOB
     */
    public void setAdjuntoClob(ClobDomain value) {
        setAttributeInternal(ADJUNTOCLOB, value);
    }

    /**
     * Gets the attribute value for ADJUNTO_EXTENSION using the alias name AdjuntoExtension.
     * @return the ADJUNTO_EXTENSION
     */
    public String getAdjuntoExtension() {
        return (String) getAttributeInternal(ADJUNTOEXTENSION);
    }

    /**
     * Sets <code>value</code> as attribute value for ADJUNTO_EXTENSION using the alias name AdjuntoExtension.
     * @param value value to set the ADJUNTO_EXTENSION
     */
    public void setAdjuntoExtension(String value) {
        setAttributeInternal(ADJUNTOEXTENSION, value);
    }

    /**
     * Gets the attribute value for ADJUNTO_NOMBRE using the alias name AdjuntoNombre.
     * @return the ADJUNTO_NOMBRE
     */
    public String getAdjuntoNombre() {
        return (String) getAttributeInternal(ADJUNTONOMBRE);
    }

    /**
     * Sets <code>value</code> as attribute value for ADJUNTO_NOMBRE using the alias name AdjuntoNombre.
     * @param value value to set the ADJUNTO_NOMBRE
     */
    public void setAdjuntoNombre(String value) {
        setAttributeInternal(ADJUNTONOMBRE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Mensajes.
     */
    public RowIterator getMensajes() {
        return (RowIterator) getAttributeInternal(MENSAJES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EstadosRO1.
     */
    public RowSet getEstadosRO1() {
        return (RowSet) getAttributeInternal(ESTADOSRO1);
    }
}

