package com.test.materiales.model.bc.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 07 17:23:41 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EstadosROImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EstadosROImpl() {
    }
    
    public void executeQuery() {
    
        throw new NullPointerException("PETAZO");
        
    }
}

